title: 8Planets
author: pixyzehn
author_fullname: Hiroki Nagasawa
description: A simple viewer for planetary orbits in the Solar System.
url: https://8planets.app
timezone: Asia/Tokyo

links:
  twitter: https://twitter.com/8planetsapp
  developer: https://pixyzehn.com
  jekyll: https://jekyllrb.com

sass:
  style: compressed
strict_front_matter: true

twitter:
  username: 8planetsapp
  card: summary_large_image

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

# https://jekyllrb.com/docs/configuration/default/
exclude:
- .github
- .gitignore
- .jekyll-cache
- .sass-cache
- CNAME
- LICENSE
- README.md
