title: 8Planets
author: Hiroki Nagasawa
username: pixyzehn
description: A simple viewer for planetary orbits in the Solar System.
keywords: 8Planets,Solar System Viewer,Solar System Simulator,Planetary Orbits,Widgets
url: https://8planets.app
timezone: Asia/Tokyo

links:
  twitter: https://twitter.com/8planetsapp
  developer: https://pixyzehn.com
  jekyll: https://jekyllrb.com

sass:
  style: compressed
strict_front_matter: true

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

# https://jekyllrb.com/docs/configuration/default/
exclude:
- .github
- .gitignore
- .jekyll-cache
- .sass-cache
- CNAME
- LICENSE
- README.md
