title: 8Planets
author: pixyzehn
description: A simple viewer for planetary orbits in the Solar System.
url: https://8planets.app
timezone: Asia/Tokyo

links:
  app_store: https://apps.apple.com/app/id1554639445
  app_store_review: https://apps.apple.com/app/id1554639445/?action=write-review
  twitter: https://twitter.com/BlueCometLabs
  company: https://bluecometlabs.com
  jekyll: https://jekyllrb.com

sass:
  style: compressed
strict_front_matter: true

twitter:
  username: BlueCometLabs
  card: summary_large_image

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from

# https://jekyllrb.com/docs/configuration/default/
exclude:
- .github
- .gitignore
- .jekyll-cache
- .sass-cache
- CNAME
- LICENSE
- README.md
